apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-ingress
spec:
  volumes:
  - name: work
    emptyDir: {}

  inputs:
    params:
    - name: ExternalDomain
      description: "The external domain for the EventListener e.g. `$(inputs.params.EventListenerName).PROXYIP.nip.io`"
    - name: Service
      description: "The name of the Service used in the Ingress. This will also be the name of the Ingress."
    - name: ServicePort
      description: "The service port that the ingress is being created on"
  steps:
  - name: create-ingress
    image: lachlanevenson/k8s-kubectl:latest
    command:
    - sh
    args:
    - -ce
    - |
      set -e
        cat <<EOF | kubectl create -f - || true
        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
          name: $(inputs.params.Service)
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/rewrite-target: /$1
            cert-manager.io/cluster-issuer: letsencrypt
        spec:
          tls:
          - secretName: webhook-tls
            hosts:
            - $(inputs.params.ExternalDomain)
          rules:
          - host: $(inputs.params.ExternalDomain)
            http:
              paths:
              - path: /cd
                backend:
                  serviceName: $(inputs.params.Service)
                  servicePort: $(inputs.params.ServicePort)
      EOF
