apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: conexp-pipeline
spec:
  params:
    - name: deployment-namespace
      type: string
      description: namespace to deploy the yaml
      default: conexp-mvp
    - name: fn-deployment-namespace
      type: string
      description: namespace to deploy the function yaml
      default: openfaas-fn      
    - name: git-revision
      type: string
    - name: git-url
      type: string   
    - name: web-image-source
      type: string
    - name: api-image-source
      type: string
    - name: fn-image-source
      type: string        
  workspaces:
  - name: shared-data 
  - name: docker-credentials       
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.git-url) 
      - name: revision
        value: $(params.git-revision)       
    - name: build-docker-image-web
      runAfter: ["fetch-source", "build-docker-image-fn"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data  
      - name: dockerconfig
        workspace: docker-credentials       
      params:
        - name: DOCKERFILE
          value: Contoso.Expenses.Web/Dockerfile
        - name: CONTEXT
          value: /src
        - name: IMAGE
          value: $(params.web-image-source)      
    - name: build-docker-image-api
      runAfter: ["fetch-source", "build-docker-image-web"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data  
      - name: dockerconfig
        workspace: docker-credentials      
      params:
        - name: DOCKERFILE
          value: Dockerfile
        - name: CONTEXT
          value: /src/Contoso.Expenses.API
        - name: IMAGE
          value: $(params.api-image-source)        
    - name: build-docker-image-fn
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
      - name: source
        workspace: shared-data  
      - name: dockerconfig
        workspace: docker-credentials              
      params:
        - name: DOCKERFILE
          value: Contoso.Expenses.OpenFaaS/Dockerfile
        - name: CONTEXT
          value: /src
        - name: IMAGE
          value: $(params.fn-image-source)
    - name: deploy-using-kubectl-web
      taskRef:
        name: deploy-using-kubectl
      workspaces:
      - name: source
        workspace: shared-data          
      params:
        - name: pathToYamlFile
          value: frontend.yaml
        - name: deployment-namespace
          value: $(params.deployment-namespace)
        - name: image-source
          value: $(params.web-image-source)            
    - name: deploy-using-kubectl-api
      taskRef:
        name: deploy-using-kubectl
      workspaces:
      - name: source
        workspace: shared-data         
      params:
        - name: pathToYamlFile
          value: backend.yaml
        - name: deployment-namespace
          value: $(params.deployment-namespace)
        - name: image-source
          value: $(params.api-image-source)            
    - name: deploy-using-kubectl-fn
      taskRef:
        name: deploy-using-kubectl
      workspaces:
      - name: source
        workspace: shared-data         
      params:
        - name: pathToYamlFile
          value: function.yaml
        - name: deployment-namespace
          value: $(params.fn-deployment-namespace)
        - name: image-source
          value: $(params.fn-image-source)                   
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: deployment-namespace
      description: The namespace to deploy to
    - name: image-source
      description: The path of the image      
  workspaces:
  - name: source
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s|__IMAGE__|$(params.image-source)|g;s|__SENDGRIDAPIKEY__|{SENDGRIDAPIKEYRELACE}|g;s|__APPHOSTNAME__|{APPHOSTNAMEREPLACE}|g;s|__APIDBCONSTR__|server=mysql.mysql.svc.cluster.local;Port=3306;database=conexpapi;user=ftacncf;password=FTA@CNCF0n@zure3;|g;s|__WEBDBCONSTR__|server=mysql.mysql.svc.cluster.local;Port=3306;database=conexpweb;user=ftacncf;password=FTA@CNCF0n@zure3;|g;s|__APIURL__|http://backend-svc.conexp-mvp.svc.cluster.local:80|g;"
        - "$(workspaces.source.path)/src/$(params.pathToYamlFile)"
    - name: print-yaml
      image: alpine
      command: ["cat"]
      args:
        - "$(workspaces.source.path)/src/$(params.pathToYamlFile)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.source.path)/src/$(params.pathToYamlFile)"
        - "-n"
        - "$(params.deployment-namespace)"
