apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-webhook-run
spec:
  taskRef:
    name: create-webhook
  podTemplate:
    nodeSelector:
      kubernetes.io/os: linux
  inputs:
    params:
    - name: GitHubOrg
      value: "{mygithub-org-replace}"
    - name: GitHubUser
      value: "{mygithub-user-replace}"
    - name: GitHubRepo
      value: "{mygithub-repo-replace}"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: {cicdWebhook}/cd
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
