apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: tekton-pipelines
data:
  disable-working-directory-overwrite: "true" # Tekton will not overwrite the working directory in Steps.
  enable-api-fields: alpha # Tekton will enable the API fields in Tasks and Pipelines.