apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../yml/rook-common.yaml
  - ../../../yml/rook-operator.yaml
  - ../../../yml/rook-cluster.yaml
  - ../../../yml/rook-storageclass.yaml