apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracing
resources:
  - namespace.yaml
  - release.yaml
  - ../../../yml/rook-cluster.yaml
  - ../../../yml/rook-storageclass.yaml
configMapGenerator:
- name: helm-values
  files:
  - ../../../yml/rook-values.yaml
generatorOptions:
  disableNameSuffixHash: true  