apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: '13.13.0'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  interval: 1h0m0s 
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
    valuesKey: rook-values.yaml
