apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: ingress-basic
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 'v0.16.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    installCRDs: true
    nodeSelector:
      beta.kubernetes.io/os: linux
