apiVersion: v1
kind: Namespace
metadata:
  name: ingress-basic
  labels:
    cert-manager.io/disable-validation: "true"
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/trace-collector: collector.linkerd-jaeger:55678
