
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-basic
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: '4.7.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    controller:
      replicaCount: 2
      electionID: ingress-controller-leader
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: k8s.io/nginx
      ingressClass: nginx
      pod:
        annotations:
          linkerd.io/inject: enabled
          config.linkerd.io/trace-collector: collector.linkerd-jaeger:55678
      service:
        annotations:
          service.beta.kubernetes.io/azure-dns-label-name: "${appHostDnsLabel}" 
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      nodeSelector:
        beta.kubernetes.io/os: linux
    defaultBackend:
      nodeSelector:
        beta.kubernetes.io/os: linux     
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: nginx-ingress-ingress-nginx-controller
              namespace: ingress-basic 
              annotations:
                linkerd.io/inject: enabled         
