apiVersion: v1
kind: Namespace
metadata:
  name: conexp-mvp
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/trace-collector: "collector.linkerd-jaeger:55678"
    config.alpha.linkerd.io/trace-collector-service-account: "collector"
