
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-nginx-ingress
  namespace: harbor-ingress-system
spec:
  releaseName: harbor-nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: '3.23.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    controller:
      ingressClass: harbor-nginx
      replicaCount: 2
