
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-nginx-ingress
  namespace: harbor-ingress-system
spec:
  releaseName: harbor-nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: '4.7.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    controller:
      ingressClassResource: 
        name: harbor-nginx
      replicaCount: 2
      service:
        annotations:
          service.beta.kubernetes.io/azure-dns-label-name: "${registryHostDnsLabel}"      
      nodeSelector:
        beta.kubernetes.io/os: linux
    defaultBackend:
      nodeSelector:
        beta.kubernetes.io/os: linux
