apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: conexp-mvp-devops
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.8/git-clone.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/kaniko/0.6/kaniko.yaml