
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql 
  namespace: mysql 
spec:
  releaseName: mysql 
  chart:
    spec:
      chart: mysql 
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    auth:
      rootPassword: FTA@CNCF0n@zure3
      username: ftacncf
      password: FTA@CNCF0n@zure3
    global:
      storageClass: rook-ceph-block
