apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.21.0/release.yaml
  - ../../../yml/tekton-default-configmap.yaml
  - ../../../yml/tekton-pvc-configmap.yaml
  - ../../../yml/tekton-feature-flags-configmap.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.13.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.13.0/interceptors.yaml
  - https://github.com/tektoncd/dashboard/releases/download/v0.14.0/tekton-dashboard-release.yaml