apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.49.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.24.0/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/previous/v0.24.0/interceptors.yaml
  - https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.37.0/release.yaml
patchesStrategicMerge:
  - ../../../yml/tekton-default-configmap.yaml
  - ../../../yml/tekton-feature-flags-configmap.yaml