apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openfaas
resources:
  - namespace.yaml
  - secret.yaml
  - release.yaml
  - ../../../yml/openfaas-nats-connector.yaml
configMapGenerator:
- name: helm-values
  files:
  - ../../../yml/openfaas-values.yaml
