
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor-system
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: '1.6.0'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3 
  values:
    expose:
      tls:
        secretName: ingress-cert-harbor
      ingress:
        annotations:
          kubernetes.io/ingress.class: harbor-nginx 
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          core: "${registryHost}"
    notary:
      enabled: false
    trivy:
       enabled: false
    persistence:
      enabled: true
      persistentVolumeClaim:
        chartmuseum:
          storageClass: rook-ceph-block
        jobservice:
          storageClass: rook-ceph-block
        database:
          storageClass: rook-ceph-block
        redis:
          storageClass: rook-ceph-block
        registry:
          storageClass: rook-ceph-block
    externalURL: "${externalUrl}"
    harborAdminPassword: admin
