apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-devops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: app-core
    - name: infrastructure-tekton
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/app/devops
  postBuild:
    substitute:
      cicdWebhookHost : "app-cna-gitops.eastus.cloudapp.azure.com"
      registryHost: "harbor-cna-gitops.eastus.cloudapp.azure.com"
      appHostName: "app-cna-gitops.eastus.cloudapp.azure.com"
      sendGridApiKey: "JustAnotherKey"  
  prune: true
  validation: client