apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-nginx
    - name: infrastructure-harbor
    - name: infrastructure-mysql
    - name: infrastructure-linkerd
    - name: infrastructure-openfaas
    - name: infrastructure-seed
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/app/core
  prune: true