apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-devops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: app-core
    - name: infrastructure-tekton
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/app/devops
  postBuild:
    substitute:
      cicdWebhookHost : "{cicdWebhookHost}"
      registryHost: "{registryHost}"
      appHostName: "{appHostName}"
      sendGridApiKey: "{sendGridApiKey}"   
  prune: true
  validation: client