apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-devops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: app-core
    - name: infrastructure-tekton
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/app/devops
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gitops-variables  
  prune: true
  validation: client
