apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-tekton
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-rook  
    - name: infrastructure-nginx     
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/tekton
  prune: true
  validation: client
