apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-certmanager-issuer
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-certmanager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/cert-manager-issuer
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gitops-variables
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
