apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-knative
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/knative
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gitops-variables
  prune: true