apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-rook
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/rook
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-0
      namespace: rook-ceph
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-1
      namespace: rook-ceph
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-2
      namespace: rook-ceph            
