apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-harbor
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-harbor-nginx
    - name: infrastructure-rook
    - name: infrastructure-linkerd    
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/harbor
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gitops-variables
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: harbor
      namespace: harbor-system
