apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/nginx
  prune: true
  validation: client
  postBuild:
    substitute:
      appHostDnsLabel : "{appHostDnsLabel}"  
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: nginx-ingress
      namespace: ingress-basic
