apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-rook
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-sources  
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/rook
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gitops-variables
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: rook-ceph
      namespace: rook-ceph