apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-rook-cluster
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-rook
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/rook-cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: gitops-variables
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: rook-ceph
      namespace: rook-ceph     
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-0
      namespace: rook-ceph
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-1
      namespace: rook-ceph
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-osd-2
      namespace: rook-ceph