apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-openfaas
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-rook    
    - name: infrastructure-nginx   
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/openfaas
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: openfaas
      namespace: openfaas
