apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/opaque-ports: "4222"
    config.linkerd.io/trace-collector: collector.linkerd-jaeger:55678
  labels:
    role: openfaas-system
    access: openfaas-system