apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.10.2/serving-core.yaml
  - https://github.com/knative/net-kourier/releases/download/knative-v1.10.0/kourier.yaml
  - https://github.com/knative/eventing/releases/download/knative-v1.10.1/eventing-core.yaml
patches: 
  - patch: |-
      - op: replace
        path: /data
        value: {"ingress-class":"kourier.ingress.networking.knative.dev"}                 
    target:
      version: v1
      kind: ConfigMap 
      name: config-network
  - patch: |-
      - op: replace
        path: /data
        value: {"example.com":""}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-domain     
  - patch: |-
      - op: replace
        path: /data
        value: {"enable-scale-to-zero": "true"}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-autoscaler   
  - patch: |-
      - op: replace
        path: /data
        value: {}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-observability        
  - patch: |-
      - op: replace
        path: /data
        value: {}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-tracing          
  - patch: |-
      - op: replace
        path: /data
        value: {}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-logging      
  - patch: |-
      - op: replace
        path: /data
        value: {}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-gc
  - patch: |-
      - op: replace
        path: /data
        value: {}              
    target:
      version: v1
      kind: ConfigMap 
      name: config-leader-election             