apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    config.json: AgA5fyKB6YudO8url+8mz6dbo7RbxEbauj5ZHRNGfgQOF1N1Tno3VqCCBSZdFr2b9dgZyog7NbIWccJNm/2RuIYiG+rNa6wdXG1z4SfI0A/OS6j/j6aUPXfVDAPTHHoTYUUsFz2eJHdcu8nCLwRs6JolMkbTAIjJ1TFImU9fV9Mb4DuYdKvEK5dUih/aQsAVPG8NlvV0VQ+G5MVKi8EThDS9R3r2djHio+GoxqlIYZsYQbeGfABcJV9Mu+ijtFRA/kGOZrG93so76XOKyWBqm8hlFXcqfMhLZHKrR4QL1zdp/s5tsifDreHJQ6myrrMEuDhYsK+uXN+FwNI8yjtwQP4ijdEkJyc1pWFVMwK6fw8qgPAWHfSV6LnSBR5E+47RIbWY8zxY66/nGwRx3O5k00keX1NwftWUXyT4de2AoooLyLVWpUmK4Gjn44HUqaYdp2qqhHMPklUC4AT9FUxBKK1CUjh+FDekZ1rRvZFe1vT22rifEmzH4rJtQ1tvp8d8FqvuxIzTzVXAbA+eEaoBo64VhM1u5vT6grO0h+ZTQ/+P3DTwtpMvWI4vZOatIPIPsTqVZxYrraUIfeqy4jGO6HEKp6kgGUWQFVHhQIox/4KlffcQKOdFQLYgq7gwGm7IprHnPFeyMXOze2+cVeQX9V7wi6o7bQNJnTLSp3wfTz45jWtbofWPZaiXGahoH+c11R7N45x9rVe4iW1z3tquHcpZttMUZABn/CLdvfXoyHVb6tFggQD97suxkvjWnDA//dSjb+pctiOf56BOpT8yhA4Z9yMK1S0jjSgvIADBgDX32dESRjs305FDesOKY4Vmix4JYdCfHh+g0T6szIy6pG5C5KghZSI/MVnW4bysspw0AR3QUZA0zqRmbw43pom6yUIt3lw3nK6UAa+BDS9FlzSFO/bduMfDV8lvcfqtHsIU0DXgOwVYpUnaBbE1/arXbVj1knZB1psriHV3/QPszVsXy/wNpE5oI0EFPEV2biqjql10kZMZAjyrmO/uA1BDmtU7tqzDHGIbKp3fQaEbTwCIVSGUJe+WvkbN380efxS/nnoP
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default

