apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    config.json: AgBlDYfFf9La8lwWWSamKkNNM7k11TE8ipjw5lJswEDQb3iEaTIJqevvSAhiELB2JcWLgIbaadr/vWIXNXhLAcKWg4vCb5v3dx8Om3T3LeQQ2Bh+QNvX+SAmqzsV+GuA+Or01FgvSd2bwbM6LsYrKIBIGNjuxNEKm2jlSlTba58H04D757D1mXPUKoUo9dwcDGNI0I0gTpurHg619hL9V3j8KXGaO1VVX9L9R0sFcwgfU8hduuIPdjOpIw7GHqA42FFbdpTPNf9nujFK5ddDtXFK2cBRoayCN5IbT/Y0nulLQUoiBur6Bl4Eu69YEj6m2N/gywKitVNVgtM3MRkDNEmE4HiZ1bNvnZo5i19LgYfe1VthQ9cBiYpPVAJlwdsIwsfyD/cB982Bx93hhrRVrIvzM0/b8IjyEvA9hRGC6EYJ1bukLnTI17ZUzdLeEZrlywAgsGi9zFZtzLHGQPg3nZ8kmrHl5nMtNcEv/PKwayjrVJ9RhuFhT7XXiJZ/eP/78iPZm2t27qwutTnuyG9OiKVfcLU8aE3wAOFrR9yVmYpoXwR3LLj22GVve9NDBD2UdR+PzG0k5A+k3t7TISz+PAYMpp0FGpFFMXBhuiwQ4Lw6Ox1nmjiCrLv+kzSR+frFJWV/AdeljqPr4MNfJYSg23NXoRx7xlGnBq/C5swV5+HSXy74AZSrKz8NX/yZgryYcu+L7zAsFKzkA3mwfqgiErWDoTFoRVT2SLPiRSCR0PlstoCu6JGdpSIb0nFTsZbGbGM0RIv/7SOiFG/zKltCczg1LsVw5CKnCoGxWdn8kPMPmwSeiwAoieVSGbcfuMU4ow+IJBHKFsNf1pB9CXCc+2zToST9G5mJhvlew3tnorraXMgrcje5/f6tIOIzlJPaeAYzu0FArOhMTZKeZzB2fg6OsMdwwmD/4cZ/oJUxXPQJeryye+KO/ZXKBujt85Zilf2PdNOXOpvfGN1PA3mjg0SGOdmwWyjTUbskwVdINNa3hJLqcpkzqSvxx1ui3ZqdTZwcecQe1REn3IosPMY6n2FR+LCOrHYE/SmICWnHEfXPZRd8
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default

