apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    config.json: AgAumc3WB8a9/rV0+EtuXU4BjHDBdvIJ9foZ33ex2kTXIhvnk97dWMVuk4EUXOSFh5ghwgJSoo5GGnY0TqS5cFtYDxIq6BtfREipljEF9uJG2XFn1ed7X7hCLr7rKUtbdYjUzUKr9KjZbro1wJLNVVCa5RJQDSdbAdotXgx8ETz51M67mmdWLiwllPQ4TNro/2q7ZUra+aZSJxSiluOodcc+x5iWY4qhvfOvrGQOdTbkUwYNvILI8XpMv19Wk8TpuPoMp6CIlzwPKco7H9+cvLplrI7RGM2w01z8uUiy5v1kxM11AFlBo5YtwLqWxU7BMRWooEafSEC3Cq313cofdcpnaNcH7xberqj75LC+Ino928EGrVk2MlSrLRlEysgimThPGdoWOaWCGVZiVM9vge8G5+L7dfEbG+uBRlXeYGU7vK/4jPJ7mCfh0pd2MI/0Zec5r9gowLP9FBK2wZEQax/bEGIzqEVGEe/LhjUIIGWuImsEsXhO1l94ohrH6K3BvYscGdAmRrYLDwXcawOZoGIkz9jhzmhPzDIddQ++gB/u4+rbIhnZzf+1o7z5omxKLDH8aciPzsn8dzHHFHn4giwtG3fLi6fBGE90X6rp+z63OJGQRLAdTh9BzKLwKzyvvpXHFL09P2yah47L0GV0Mdcj9ATtWmZpjurdHQd3a28mID3SmaRmtVpQAWObCXYmNn7qhUtDL2lHlgCd++7HJoDRhen/Yogyzg9L2RfuEXjEXoCW4CDpkmOFKNpbu43XyYeTfup0sUVQ7YBLI2uR+CEYtTCDPkqb4oLKqjNB9qSNkO45YOST6RvzZhN9X/cNpiNsFscIQ5Nt46Da6xrBi3WULcc0TkrhKu0ffmyjki1Fqx2X6GmDhlBJjEPUCsazVgdVKVRDMRvXYoYfB2Qq7701pAHFg1TKAjgplakd2fQBl1URdqWmA1u1/xEu99C9WbhVE93240ZnglNpQbahLmhTyOaxagL8DHZISkc0mBOSi5PuBuEQetbqy2KZjptUPEmVUtKKgNT2Du8NCYOESF36X2yNl4494WHFho/gNFRLXA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default

