apiVersion: v1
kind: Namespace
metadata:
  name: nats
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/skip-outbound-ports: "4222"
    config.linkerd.io/trace-collector: collector.linkerd-jaeger:55678
