apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracing
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
- name: helm-values
  files:
  - ../../../yml/jaeger-values.yaml
generatorOptions:
  disableNameSuffixHash: true