apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: tracing
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      version: '0.71.8'
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
    valuesKey: jaeger-values.yaml