apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ingress-basic
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${cluster_issuer_email}"
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress: {}   
