
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd 
spec:
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      version: '1.6.1'       
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h0m0s   
  install:
    remediation:
      retries: 3
