
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger 
  namespace: linkerd 
spec:
  releaseName: linkerd-jaeger 
  chart:
    spec:
      chart: linkerd-jaeger
      version: '30.8.5'        
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h0m0s
  dependsOn:
    - name: linkerd   
  install:
    remediation:
      retries: 3    
  values:
    jaeger:
      enabled: false
    collector:
      jaegerAddr: http://jaeger-collector.tacing:14268/api/traces
