
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger 
  namespace: linkerd 
spec:
  releaseName: linkerd-jaeger 
  chart:
    spec:
      chart: linkerd-jaeger
      version: '2.10.0'        
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h0m0s
  dependsOn:
    - name: linkerd   
  install:
    remediation:
      retries: 3    
  values:
    jaeger:
      enabled: false
    collector:
      config: |
        receivers:
          otlp:
            protocols:
              grpc:
              http:
          opencensus:
          zipkin:
          jaeger:
            protocols:
              grpc:
              thrift_http:
              thrift_compact:
              thrift_binary:
        processors:
          batch:
        extensions:
          health_check:
        exporters:
          jaeger:
            endpoint: jaeger-collector.tracing:14250
            insecure: true
        service:
          extensions: [health_check]
          pipelines:
            traces:
              receivers: [otlp,opencensus,zipkin,jaeger]
              processors: [batch]
              exporters: [jaeger] 
