
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd 
  namespace: linkerd 
spec:
  releaseName: linkerd 
  chart:
    spec:
      chart: linkerd2 
      version: '2.9.4'
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: certs
      valuesKey: ca.crt
      targetPath: global.identityTrustAnchorsPEM
    - kind: Secret
      name: certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM      
  values:
    installNamespace: false
    prometheus:
      enabled: false
    identity:
      issuer:
        crtExpiry: ${cert_expiry}    
