apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: expenseemailsender
  namespace: conexp-mvp-fn
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred  
      containers:
      - image: __IMAGE__
        env:
        - name: SENDGRID_API_KEY
          value: "__SENDGRIDAPIKEY__"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: dispatch-email
  namespace: conexp-mvp-fn
spec:
  broker: default
  filter:
    attributes:
      type: dispatch-email
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: dispatch-email          