apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: expenseemailsender
spec:
  name: expenseemailsender
  annotations:
    topic: "nats-email"
  image: __IMAGE__
  environment:
    write_debug: "true"
    SENDGRID_API_KEY: "__SENDGRIDAPIKEY__"
  secrets:
      - regcred
