apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
- name: helm-values
  files:
  - ../../../yml/prometheus-values.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: prometheus-kube-prometheus-prometheus-scrape-confg-linkerd
  files:
  - additional-scrape-configs.yaml=../../../yml/linkerd-prometheus-additional.yaml