apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '13.13.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
    valuesKey: prometheus-values.yaml
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: ServiceMonitor
            apiVersion: monitoring.coreos.com/v1
            metadata:
              name: prometheus-kube-prometheus-kubelet
            spec:
              endpoints:
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                interval: 10s
                port: https-metrics
                scheme: https
                tlsConfig:
                  insecureSkipVerify: true
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                honorLabels: true
                interval: 10s
                path: /metrics/cadvisor
                port: https-metrics
                scheme: https
                tlsConfig:
                  insecureSkipVerify: true
          - kind: Prometheus
            apiVersion: monitoring.coreos.com/v1
            metadata:
              name: prometheus-kube-prometheus-prometheus
            spec:
              additionalScrapeConfigs:
                name: prometheus-kube-prometheus-prometheus-scrape-confg-linkerd                