apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: conexp-mvp
spec:
  encryptedData:
    .dockerconfigjson: AgCn8dHNNewRHqRYAJgbF2E6kA4GFYNeSCeHkUAGpZohhDjM6QTwerXv3SpyJTdiR8I9VA++cTsvE1D8lK3z3ZheLS0CBFMxl6GMA7qxtKiEntNJ6ouWponXok58CouhHqf+0sv0D9qxjB17wnctKBVl8Nj2IBGJJOW7F+PgZQsQNb72bAbzXkLoB3vPLpAgSmAlHo7ywFHXAu6cnwAi46/QfqN6C6orQuzDOrHhi8VSqcFEAHf+hZ+JdJgzyD1IlnOUedMt0XNQfe1BbjcW8wb/zZIIZiDt+O0wSSACsxpe/axRvEp6LBh8uPGW/gbKP0j5AI11nQ3vxJ/efAz9fcTUBPWddywT7/tOTzDgnGwt0I6KFxdx4haN0ZhX62uH02hmO/HiQKHGzSg/Co8XuI9VLUaKU5NdF0KeUoYnzFod0Wu/3V86yFGxY2f55DJFKN82PdKAxC1pjtSn/40CbTBtOj5YJU4nOnV/SzD2T5pmxuyxirotft4lROdsl2nkp3PJZQKvgc657TUyNA42DnRspR5olRGCnu6ldm385BoBJUnanPiLaGa9zF3dPqxHdUkgb8sYwErXnbBqgWRSu8bVEArzrTvMdITCPwy2TF1lUk5jK1ONpNRHopA9pe+Azmf9tswhduquaseGcIgZ5MqoL7+O353b5yLKFmsl2Hu4zSNJV4ENjWrGMh8A4anWGqKLiSeZVAmSQHfXaRHxZdL1zLTumcqYJjfk9rjP7QENt/iyGR467oZybFFz4xDxSPcSE0gpI19zAaiG3SNKG7mstA0LIZzydwzvoZGP6fgEbY7+lixK3EoGf4lqNxEfIKvWHOhkuXhqNGE658QRO4e+PhDyMVaxpksDwGB5IWTt0Mq5N280c2ilqkU9CvIhASrpsVfulFdTVXvW2ZMN9iS5fMyqmS4YIxet7+xC1o6I83zaRtMjECpnXIS0tm3DJuc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: conexp-mvp
    type: kubernetes.io/dockerconfigjson

